services:
  aasd_server:
    image: tigase/tigase-xmpp-server:8.0.0
    container_name: tigase_server
    ports:
      - "8480:8080" # Admin panel/web interface
      - "5422:5222" # XMPP client connections
    environment:
      - DB_ROOT_USER=admin
      - DB_ROOT_PASS=admin
      - ADMIN_JID=admin@aasd_server
      - ADMIN_PASSWORD=admin
    volumes:
      - ./tigase/config/tigase.conf:/home/tigase/tigase-server/etc/tigase.conf
      - ./tigase/config/config.tdsl:/home/tigase/tigase-server/etc/config.tdsl
    networks:
      - aasd_network

  aasd_system:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: spade_agent
    depends_on:
      - aasd_server
      - aasd_mongodb
    deploy:
      resources:
        limits:
          memory: 512MB
    environment:
      - SPADE_AGENT_JID=admin@aasd_server
      - SPADE_AGENT_PASSWORD=admin
    volumes:
      - ./logs:/app/logs:rw
    networks:
      - aasd_network

  aasd_mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - ~/aasd_mongo:/data/db
    networks:
      - aasd_network

networks:
  aasd_network: